# Generated by Django 3.2.4 on 2022-06-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='post',
        ),
    ]
