# Generated by Django 3.2.4 on 2022-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone3',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
