# Generated by Django 3.2.4 on 2022-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_phone3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone3',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(max_length=50),
        ),
    ]
