# Generated by Django 3.2.4 on 2022-06-17 10:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220617_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiment_no', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=app.models.shipment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
