# Generated by Django 3.2.4 on 2022-06-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_shiment_no_shipment_shipment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='document_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
